shoulder_pan_joint_controller:
  type: position_controllers/JointPositionController
  joint: shoulder_pan_joint
  pid:
    p: 100.0
    d: 10.0
shoulder_lift_joint_controller:
  type: position_controllers/JointPositionController
  joint: shoulder_lift_joint
  pid:
    p: 100.0
    d: 10.0
elbow_joint_controller:
  type: position_controllers/JointPositionController
  joint: elbow_joint
  pid:
    p: 100.0
    d: 10.0
wrist_1_joint_controller:
  type: position_controllers/JointPositionController
  joint: wrist_1_joint
  pid:
    p: 100.0
    d: 10.0
wrist_2_joint_controller:
  type: position_controllers/JointPositionController
  joint: wrist_2_joint
  pid:
    p: 100.0
    d: 10.0
wrist_3_joint_controller:
  type: position_controllers/JointPositionController
  joint: wrist_3_joint
  pid:
    p: 100.0
    d: 10.0
