# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - motor_S_joint
    - motor_L_joint
    - motor_U_joint
    - motor_R_joint
    - motor_B_joint
    - motor_T_joint
    - finger1_joint
    - finger2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - motor_S_joint
      - motor_L_joint
      - motor_U_joint
      - motor_R_joint
      - motor_B_joint
      - motor_T_joint


arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - motor_S_joint
    - motor_L_joint
    - motor_U_joint
    - motor_R_joint
    - motor_B_joint
    - motor_T_joint
  gains:
    motor_S_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_L_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_U_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_R_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_B_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_T_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

finger1_controller:
  type: effort_controllers/JointPositionController
  joint: finger1_joint
  pid:
    p: 1000
    d: 1
    i: 1
    i_clamp: 1

finger2_controller:
  type: effort_controllers/JointPositionController
  joint: finger2_joint
  pid:
    p: 1000
    d: 1
    i: 1
    i_clamp: 1