hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - sh_finger1_joint
    - sh_finger2_joint
  gains:
    sh_finger1_joint:
      p: 10000
      d: 5
    sh_finger2_joint:
      p: 10000
      d: 5