finger1_joint_controller:
  type: effort_controllers/JointPositionController
  joint: finger1_joint
  pid:
    p: 1000.0
    d: 10.0
finger2_joint_controller:
  type: effort_controllers/JointPositionController
  joint: finger2_joint
  pid:
    p: 1000.0
    d: 10.0
