<robot name="arm_shand" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="wrist_length" value="0.02"/>
  <xacro:property name="palm_thick" value="0.02"/>
  <xacro:property name="finger_x" value="0.08"/>
  <xacro:property name="finger_y" value="0.02"/>
  <xacro:property name="finger_length" value="0.1"/>
  <xacro:property name="finger_lower" value="${finger_y/2}"/>
  <xacro:property name="finger_upper" value="${finger_y/2 + 0.08}"/>
  <xacro:property name="finger_mass" value="5"/>
  <xacro:property name="finger_effort" value="500.0"/>
  <xacro:property name="finger_vel" value="${pi}"/>


  <xacro:include filename="$(find arm_description)/urdf/arm_description.urdf.xacro"/>

  <xacro:macro name="prismatic" params="name parent child xyz rpy axis lower upper">
    <joint name="${name}" type="prismatic">
      <parent link="${parent}"/>
      <child link="${child}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="${axis}"/>
      <limit effort="${finger_effort}" velocity="${finger_vel}" lower="${lower}" upper="${upper}"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <transmission name="${name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
  <xacro:macro name="finger" params="name parent length xyz rpy">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${finger_x} ${finger_y} ${length}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_x} ${finger_y} ${length}"/>
        </geometry>
      </collision>
      <cylinder_inertial
              radius="${finger_x/4+finger_y/4}"
              length="${length}"
              mass="${finger_mass}"
      />
    </link>
    <prismatic
            name="${name}_joint"
            parent="${parent}"
            child="${name}"
            xyz="${xyz}"
            rpy="${rpy}"
            axis="0 1 0"
            lower="${finger_lower}"
            upper="${finger_upper}"
    />
    <gazebo reference="${name}">
      <material>Gazebo/White</material>
    </gazebo>
  </xacro:macro>
  <xacro:macro name="palm" params="name parent xyz rpy">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${finger_x} ${finger_upper*2} ${palm_thick}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_x} ${finger_upper*2} ${palm_thick}"/>
        </geometry>
      </collision>
      <cylinder_inertial
              radius="${finger_x/4+(finger_upper*2)/4}"
              length="${palm_thick}"
              mass="${finger_mass}"
      />
    </link>
    <fixed
            name="${name}_joint"
            parent="${parent}"
            child="${name}"
            xyz="${xyz}"
            rpy="${rpy}"
    />
    <gazebo reference="${name}">
      <material>Gazebo/White</material>
    </gazebo>
  </xacro:macro>

  <!-- simple hand -->

  <xacro:macro name="arm_shand">

    <arm/>
    <pole
            name="sh_wrist"
            parent="wrist_link"
            length="${wrist_length}"
            xyz="0 0 ${wrist_length/2}"
            rpy="0 0 0"
    />
    <palm
            name="sh_palm"
            parent="sh_wrist"
            xyz="0 0 ${wrist_length/2 + palm_thick/2}"
            rpy="0 0 0"
    />

    <!-- end effector -->
    <finger
            name="sh_finger1"
            parent="sh_palm"
            length="${finger_length}"
            xyz="0 0 ${palm_thick/2 + gap + finger_length/2}"
            rpy="0 0 3.1415926"
    />
    <finger
            name="sh_finger2"
            parent="sh_palm"
            length="${finger_length}"
            xyz="0 0 ${palm_thick/2 + gap + finger_length/2}"
            rpy="0 0 0"
    />

  </xacro:macro>

</robot>
